# Request
int32 axis_index
float64 target_pose
float64 threshold
string profile
float64 velocity
float64 acc
float64 dec
---
# Result
bool success
float64 final_pose
string message
---
# Feedback
float64 current_pose