diff_drive_controller:
  ros__parameters:
    left_axis: 0
    right_axis: 1
    rate: 100

    acc_time: 1.0
    dec_time: 1.0
    wheel_radius: 0.09
    wheel_to_wheel: 0.55

    cmd_vel_topic: /cmd_vel
    encoder_vel_topic: /cmd_vel_check
    encoder_omega_topic: /velocity_controller/commands
    encoder_odometry_topic: /odom_enc

    wmx_param_file_path: /home/mic-713/wmx_ros2_ws/src/wmx_ros2_application/wmx_ros2_package/config/baymax_wmx_parameters.xml
    