differential_drive_controller:
  ros__parameters:
    left_axis: 0
    right_axis: 1
    rate: 100
    acc_time: 1.0
    dec_time: 1.0
    wheel_radius: 0.095
    wheel_to_wheel: 0.55
    cmd_vel_topic: /cmd_vel
    encoder_odometry_topic: /odom_encoder
    encoder_omega_topic: /omega_enc
    wmx_param_file_path: ""  # resolved at launch time via get_package_share_directory

joint_state_broadcaster:
  ros__parameters:
    joint_feedback_rate: 100
    joint_axes: [0, 1]
    joint_name: ["drivewheel_left_joint", "drivewheel_right_joint"]
    encoder_joint_topic: /joint_states
    isaacsim_joint_topic: /isaacsim/joint_command
    gazebo_joint_topic: /velocity_controller/commands
