manipulator_state:
  ros__parameters:
    joint_number: 6
    joint_feedback_rate: 100
    joint_name: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "picker_1_joint", "picker_2_joint"]
    encoder_joint_topic: /joint_states
    isaacsim_joint_topic: /isaacsim/joint_command