manipulator_state:
  ros__parameters:
    joint_number: 6
    joint_feedback_rate: 500
    gripper_open_value: 0.00
    gripper_close_value: 0.045
    joint_name: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "picker_1_joint", "picker_2_joint"]
    encoder_joint_topic: /joint_states
    isaacsim_joint_topic: /isaacsim/joint_command
    wmx_param_file_path: /home/mic-743/wmx_ros2_ws/src/wmx_ros2_application/wmx_ros2_package/config/cr3a_wmx_parameters.xml

follow_joint_trajectory_server:
  ros__parameters:
    joint_number: 6
    wmx_gripper_topic: /wmx/set_gripper
    joint_trajectory_action: /movensys_manipulator_arm_controller/follow_joint_trajectory